config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json {rubycritic render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RailsSassTest
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{:href => "#"}
            %span.glyphicon.glyphicon-globe{"aria-hidden" => "true"}
            Brand

        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"}
                Link active
            %li
              %a{:href => "#"} Link

          %ul.nav.navbar-nav.navbar-right
            %li
              %a{:href => "#"} Link
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Dropdown
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  %a{:href => "#"} Action
                %li
                  %a{:href => "#"} Another action
                %li
                  %a{:href => "#"} Something else here
                %li.divider
                %li
                  %a{:href => "#"} Separated link

    = yield

app/views/todos/_form.html.haml
= form_for @todo do |f|
  - if @todo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@todo.errors.count, "error")} prohibited this todo from being saved:"
      %ul
        - @todo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :notes
    = f.text_area :notes
  .actions
    = f.submit 'Save'

app/views/todos/edit.html.haml
%h1 Editing todo

= render 'form'

= link_to 'Show', @todo
\|
= link_to 'Back', todos_path

app/views/todos/index.html.haml
%h1 Listing todos

%table
  %thead
    %tr
      %th Title
      %th Notes
      %th
      %th
      %th

  %tbody
    - @todos.each do |todo|
      %tr
        %td= todo.title
        %td= todo.notes
        %td= link_to 'Show', todo , class:'btn btn-success' 'btn btn-primary btn-xs'
        %td= link_to 'Edit', edit_todo_path(todo), class:'btn btn-success' 'btn btn-primary btn-xs'
        %td= link_to 'Destroy', todo, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs'

%br

= link_to 'New Todo', new_todo_path, class:'btn btn-success'

app/views/todos/new.html.haml
%h1 New todo

= render 'form'

= link_to 'Back', todos_path

app/views/todos/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @todo.title
%p
  %b Notes:
  = @todo.notes

= link_to 'Edit', edit_todo_path(@todo)
\|
= link_to 'Back', todos_path